version: '3'

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!
    volumes:
      - ./config/:/etc/traefik/
      - traefik-ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: nginx
    ports:
       - "81:80"  
       - "444:443"         
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nginx.entrypoints=web,websecure'
      - 'traefik.http.routers.nginx.rule=Host("tudominio.com")'
      - 'traefik.http.routers.nginx.tls=true'     
      - 'traefik.http.routers.nginx.tls.certresolver=production'   

volumes:
  traefik-ssl-certs:
    driver: local
    
    
